ViridianCity_PokemonCenter_1F_Text_FeelFreeToUsePC::
    .string "Please feel free to use that PC in\n"
    .string "the corner.\p"
    .string "The receptionist told me so.\n"
    .string "It's so kind of her!$"

ViridianCity_PokemonCenter_1F_Text_PokeCenterInEveryTown::
    .string "There's a POKéMON CENTER in every\n"
    .string "town ahead.\p"
    .string "They charge no money, so don't\n"
    .string "be shy about healing POKéMON.$"

ViridianCity_PokemonCenter_1F_Text_PokeCentersHealMons::
    .string "POKéMON CENTERS heal your tired,\n"
    .string "hurt, or fainted POKéMON.\p"
    .string "They make all POKéMON completely\n"
    .string "healthy.$"

ViridianCity_PokemonCenter_1F_Text_ImFishingGuruDoYouLikeToFish::
    .string "I'm the FISHING GURU!\p"
    .string "I moved here from the MART\n"
    .string "because POKéMON CENTERS are\l"
    .string "much more peaceful.\p"
    .string "Plus, trainers here understand\n"
    .string "the bond between people and\l"
    .string "POKéMON, just like fishing!\p"
    .string "I simply looove fishing!\n"
    .string "I can't bear to go without.\p"
    .string "Tell me, do you like to fish?$"

ViridianCity_PokemonCenter_1F_Text_TakeThisAndFish::
    .string "Grand! I like your style.\n"
    .string "I think we can be friends.\p"
    .string "Take this and fish, young friend!$"

ViridianCity_PokemonCenter_1F_Text_ReceivedOldRodFromFishingGuru::
    .string "{PLAYER} received an OLD ROD from\n"
    .string "the FISHING GURU.$"

ViridianCity_PokemonCenter_1F_Text_FishingIsAWayOfLife::
    .string "Fishing is a way of life!\n"
    .string "It is like the finest poetry.\p"
    .string "From the seas to rivers, go out\n"
    .string "and land the big one, my friend.$"

ViridianCity_PokemonCenter_1F_Text_OhThatsSoDisappointing::
    .string "Oh…\n"
    .string "That's so disappointing…$"

ViridianCity_PokemonCenter_1F_Text_HowAreTheFishBiting::
    .string "Hello there, {PLAYER}!\p"
    .string "I'm so glad I moved here from\n"
    .string "the MART. Much quieter!\p"
    .string "How are the fish biting?$"

ViridianCity_PokemonCenter_1F_Text_NoRoomForNiceGift::
    .string "Oh, no!\p"
    .string "I had a nice gift for you, but you\n"
    .string "have no room for it!$"

