name: CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GAME_VERSION: FIRERED
      GAME_LANGUAGE: ENGLISH
      GAME_REVISION: 0
      MODERN: 0
      COMPARE: 0
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout agbcc
        uses: actions/checkout@v4
        with:
          path: 'agbcc'
          repository: 'pret/agbcc'

      - name: Install binutils
        run: sudo apt install gcc-arm-none-eabi binutils-arm-none-eabi libpng-dev

      - name: Install agbcc
        run: |
          ./build.sh
          ./install.sh ../
        working-directory: ./agbcc

      - name: Compare FireRed
        continue-on-error: true
        run: |
          make -j$(nproc) all syms

      - name: Compare FireRed rev1
        continue-on-error: true
        env:
          GAME_REVISION: 1
        run: |
          make -j$(nproc) all syms

      - name: Compare LeafGreen
        continue-on-error: true
        env:
          GAME_VERSION: LEAFGREEN
        run: |
          make -j$(nproc) all syms

      - name: Compare LeafGreen rev1
        continue-on-error: true
        env:
          GAME_VERSION: LEAFGREEN
          GAME_REVISION: 1
        run: |
          make -j$(nproc) all syms

      - name: Build Modern
        env:
          MODERN: 1
          COMPARE: 0
        run: |
          make -j$(nproc) all

      - name: Upload build artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: pokemon-roms
          path: |
            *.gba
            *.sym
          retention-days: 30
